name: rechorus
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10.4
  - pytorch=1.12.1
  - cudatoolkit=11.3.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - numpy=1.22.3
  - pandas=1.4.4
  - scipy=1.7.3
  - scikit-learn=1.1.3
  - pyyaml=6.0.3
  - pip
  - pip:
      - tqdm==4.66.1